seed = 0
parent_dir = "exp/abalone/check"
real_data_path = "data/abalone/"
model_type = "mlp"
num_numerical_features = 7
device = "cuda:0"

[model_params]
is_y_cond = false
d_in = 11
num_classes = 0

[diffusion_params]

[model_params.rtdl_params]
num_layers = 1  # Entity encoder layers for entity Encoder
field_encoder_layers = 1  # number of layers for field encoders
field_decoder_layers =  1  # number of layers for field decoders
num_decoder_mixtures = 32   # number of gaussian mixtures for numerical features
d_model = 256
dropout = 0.0

[train.main]
steps = 4_000
lr = 1e-3
weight_decay = 0
batch_size = 4096

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 20800
batch_size = 10000
seed = 0

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
