seed = 1
parent_dir = "exp/churn2/check"
real_data_path = "data/churn2/"
model_type = "mlp"
num_numerical_features = 7
device = "cuda:1"

[model_params]
num_classes = 2
is_y_cond = true

[model_params.rtdl_params]
num_layers = 1  # Entity encoder layers for entity Encoder
field_encoder_layers = 1  # number of layers for field encoders
field_decoder_layers =  1  # number of layers for field decoders
num_decoder_mixtures = 32   # number of gaussian mixtures for numerical features
d_model = 256
dropout = 0.0

[diffusion_params]

[train.main]
steps = 4_000
lr = 1e-3
weight_decay = 0
batch_size = 4096

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 26000
batch_size = 10000
seed = 0

[eval.type]
eval_model = "simple"
eval_type = "real"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
